/**
 * Scans public/assets and regenerates app/assets.ts, so dropping an image into
 * the folder is the only step needed to bring it into the page. Runs before
 * dev, build and bundle.
 */
import { readdirSync, statSync, writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, posix, extname } from 'node:path'

const ROOT = 'public/assets'
// --inline bakes each image into the manifest as a data URI, for the single
// file build. Doing it here rather than post-processing the bundle keeps the
// server rendered markup and the client lookup table in agreement; rewriting
// the paths afterwards desynchronised them and every image fell back to its
// placeholder.
const INLINE = process.argv.includes('--inline')
const MIME = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp', '.avif': 'image/avif', '.gif': 'image/gif', '.svg': 'image/svg+xml' }
const toDataUri = (rel) => {
  const buf = readFileSync(join('public', rel.replace(/^\//, '')))
  return `data:${MIME[extname(rel).toLowerCase()] ?? 'application/octet-stream'};base64,${buf.toString('base64')}`
}
const IMAGE = /\.(?:jpe?g|png|webp|avif|gif|svg)$/i

function walk(dir, prefix = '/assets') {
  if (!existsSync(dir)) return []
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) return walk(full, posix.join(prefix, name))
    return IMAGE.test(name) ? [posix.join(prefix, name)] : []
  })
}

mkdirSync(ROOT, { recursive: true })
const found = walk(ROOT).sort()

// Key by path without extension, so a file saved as .png still satisfies a
// component asking for .jpg. Runway serves PNG; the layout names some of these
// .jpg. Without this the mismatch fails silently as a placeholder.
const byStem = {}
for (const f of found) byStem[f.replace(/\.[^./]+$/, '')] = INLINE ? toDataUri(f) : f

writeFileSync(
  'app/assets.ts',
  `/**
 * GENERATED by scripts/manifest.mjs. Do not edit by hand.
 *
 * Every image present in public/assets, keyed by path without its extension so
 * the file format does not have to match what the layout asks for. Anything
 * absent renders a marked placeholder of the right shape, so layout never
 * shifts when the real file lands.
 *
 * To add an image: drop it into public/assets and rebuild.
 */
const BY_STEM: Record<string, string> = ${JSON.stringify(byStem, null, 2)}

const stem = (src: string) => src.replace(/\\.[^./]+$/, '')

/** Is there a file for this slot, whatever its extension? */
export const hasAsset = (src: string) => stem(src) in BY_STEM

/** The real URL to use, which may differ in extension from the one requested. */
export const assetUrl = (src: string) => BY_STEM[stem(src)] ?? src

export const AVAILABLE_ASSETS = new Set<string>(Object.values(BY_STEM))
`,
)
console.log(`assets.ts: ${found.length} image(s)${INLINE ? ', inlined as data URIs' : ''}${found.length ? '\n  ' + found.join('\n  ') : ' (all placeholders)'}`)
