/**
 * GENERATED by scripts/manifest.mjs. Do not edit by hand.
 *
 * Every image present in public/assets, keyed by path without its extension so
 * the file format does not have to match what the layout asks for. Anything
 * absent renders a marked placeholder of the right shape, so layout never
 * shifts when the real file lands.
 *
 * To add an image: drop it into public/assets and rebuild.
 */
const BY_STEM: Record<string, string> = {
  "/assets/closing": "/assets/closing.jpg",
  "/assets/events/baraat": "/assets/events/baraat.jpg",
  "/assets/events/haldi": "/assets/events/haldi.jpg",
  "/assets/events/pheras": "/assets/events/pheras.jpg",
  "/assets/events/sehrabandi": "/assets/events/sehrabandi.jpg",
  "/assets/events/soiree": "/assets/events/soiree.jpg",
  "/assets/events/welcome-dinner": "/assets/events/welcome-dinner.jpg",
  "/assets/hero": "/assets/hero.jpg",
  "/assets/ornament/crest": "/assets/ornament/crest.jpg",
  "/assets/ornament/floral-column": "/assets/ornament/floral-column.jpg",
  "/assets/ornament/peacock": "/assets/ornament/peacock.jpg",
  "/assets/stay": "/assets/stay.jpg",
  "/assets/travel": "/assets/travel.jpg"
}

const stem = (src: string) => src.replace(/\.[^./]+$/, '')

/** Is there a file for this slot, whatever its extension? */
export const hasAsset = (src: string) => stem(src) in BY_STEM

/** The real URL to use, which may differ in extension from the one requested. */
export const assetUrl = (src: string) => BY_STEM[stem(src)] ?? src

export const AVAILABLE_ASSETS = new Set<string>(Object.values(BY_STEM))
